### PR TITLE
fix parsing of annotations in Java classfiles

### LINKED ISSUE #6969: Exception when compiling Java sources with SBT 1.7.0
## steps

- clone https://github.com/asflierl/java-compiler-fail.git
- run `sbt "clean;compile"`

## problem

```
> clean;compile
[info] compiling 150 Java sources to /home/asflierl/proj/java-compiler-fail/target/scala-2.13/classes ...
[error] ## Exception when compiling 150 sources to /home/asflierl/proj/java-compiler-fail/target/scala-2.13/classes
[error] java.lang.ArrayIndexOutOfBoundsException: Index 14939 out of bounds for length 61
[error] sbt.internal.inc.classfile.Parser$$anon$1.toUTF8(Parser.scala:91)
[error] sbt.internal.inc.classfile.Parser$$anon$1.parseAnnotation$1(Parser.scala:158)
[error] sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$7(Parser.scala:165)
[error] scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[error] sbt.internal.inc.classfile.Parser$$anon$1.$anonfun$annotationsReferences$4(Parser.scala:164)
[error] scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
[error] sbt.internal.inc.classfile.Parser$$anon$1.annotationsReferences(Parser.scala:136)
[error] sbt.internal.inc.classfile.Parser$$anon$1.types(Parser.scala:119)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$31(JavaAnalyze.scala:177)
[error] scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16(JavaAnalyze.scala:177)
[error] sbt.internal.inc.classfile.JavaAnalyze$.$anonfun$apply$16$adapted(JavaAnalyze.scala:108)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
[error] scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
[error] scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
[error] scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
[error] scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] sbt.internal.inc.classfile.JavaAnalyze$.apply(JavaAnalyze.scala:108)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21(AnalyzingJavaCompiler.scala:215)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$21$adapted(AnalyzingJavaCompiler.scala:207)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
[error] scala.collection.immutable.List.foreach(List.scala:431)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:207)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
[error] sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:207)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2364)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2312)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.lang.ArrayIndexOutOfBoundsException: Index 14939 out of bounds for length 61
```

## expectation

Java sources are compiled without compiler exception.

## notes

I tried this with SBT 1.6.2 and SBT 1.7.0-RC2 and both worked. Only occurs with SBT 1.7.0.
I am using JDK 17.

### PR DESCRIPTION
**Pull request by SethTisue**
* fixes sbt/sbt#6969
* sequel to sbt/zinc#1079

The test case is minimized from https://github.com/asflierl/java-compiler-fail . I have verified locally that the fix also makes compilation succeed for that repo unminimized.

I have also verified locally that this fix fixes `Test/compile` in the Play repo (https://github.com/playframework/playframework/pull/11349).

### CODE REVIEW

File: internal/zinc-classfile/src/main/scala/sbt/internal/inc/classfile/Parser.scala [hunk 1]
```diff
@@ -150,8 +150,13 @@ private[sbt] object Parser {
...
                   for (_ <- 0 until in.readUnsignedShort())
                     parseElementValue()
+                case 'B' | 'C' | 'D' | 'F' | 'I' | 'J' | 'S' | 'Z' | 's' =>
+                  val _ = in.readUnsignedShort()
                 case _ =>
-                // ignore. robustness is paramount
+                  // what to do here? perhaps robustness should be paramount, but if we encounter
+                  // something unexpected here, we're probably already doomed and attempting to
+                  // continue parsing will just make troubleshooting harder. so let's bail
+                  sys.error(s"unexpected tag in annotation: '$c'")
```
Comment (eed3si9n) [inline internal/zinc-classfile/src/main/scala/sbt/internal/inc/classfile/Parser.scala]: Could we pretend you didn't see the annotation? It's been sort of ok thus far ignoring the annotations, so sometimes ignoring it sound like a safe middle ground than blocking Java compilation even for clean compile.

Comment (SethTisue) [reply internal/zinc-classfile/src/main/scala/sbt/internal/inc/classfile/Parser.scala]: Yes, good idea, will do.

**Review by eed3si9n — APPROVED** [review]
Thanks!
