### PR TITLE
[1.x] Handle parsing of non-problems in `JavaErrorParser`

### LINKED ISSUE #1451: `JavaCompilerSpec.findsDocErrors` failing for Windows Java 17/21
c.c. https://github.com/sbt/zinc/pull/1440#issuecomment-2395822215

The issue is `JavaErrorParser.parseProblems`(in, logger) failing to parse javadoc output. Here's the problematic `in` for reference

```
Loading source file D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java...
Constructing Javadoc information...
D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java:14: error: class Test is public, should be declared in a file named Test.java
public class Test {
       ^
D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java:15: error: cannot find symbol
    public NotFound foo() { return 5; }
           ^
  symbol:   class NotFound
  location: class Test
2 errors
```

With the log, it should be possible to debug the issue on other platforms.

### PR DESCRIPTION
**Pull request by Friendseeker**
### Issue

`JavaErrorParser` assumes `javac` outputs start with a list of problems or notes. However in certain situations `javac` emits the following lines first

```
Loading source file D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java...
Constructing Javadoc information...
```

which is neither problems nor notes. The parser then gives up and parse nothing. Hence `JavaCompilerSpec` fails.

### Fix

We explicitly match for lines that start with "Loading source file" or "Constructing Javadoc information" and skip these lines before parsing problems / notes.

### Validating the fix

I tested on a Java 17 windows machine that emits the below during `JavaCompilerSpec` 

```
Loading source file D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java...
Constructing Javadoc information...
D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java:14: error: class Test is public, should be declared in a file named Test.java
public class Test {
       ^
D:\Repos\zinc\internal\zinc-compile-core\target\jvm-2.13\test-classes\sbt\internal\inc\javac\test1.java:15: error: cannot find symbol
    public NotFound foo() { return 5; }
           ^
  symbol:   class NotFound
  location: class Test
2 errors
```

The test passed locally.

Closes #1451

### CODE REVIEW

File: internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaErrorParser.scala [hunk 1]
```diff
@@ -270,10 +270,17 @@ class JavaErrorParser(relativeDir: File = new File(new File(".").getAbsolutePath
...
+      ("Loading source file" | "Constructing Javadoc information") ~ """[^\r\n]*(\r\n|\n)?""".r
+    rep(skipLine) ^^ (_ => ())
+  }
+
   val potentialProblem: Parser[Problem] =
     warningMessage | errorMessage | noteMessage | javacError | javacWarning
 
-  val javacOutput: Parser[Seq[Problem]] = rep(potentialProblem) <~ opt(outputSumamry)
+  val javacOutput: Parser[Seq[Problem]] =
+    nonProblem ~> rep(potentialProblem) <~ opt(outputSumamry)
```
Comment (eed3si9n) [inline internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaErrorParser.scala]: Should this be optional?

**Comment by eed3si9n** [comment]
Could you add test for this plz? - https://github.com/sbt/zinc/blob/1.10.x/internal/zinc-compile-core/src/test/scala/sbt/internal/inc/javac/javaErrorParserSpec.scala

**Comment by Friendseeker** [comment]
@eed3si9n Addressed PR feedback & added test!

**Review by eed3si9n — APPROVED** [review]
