### PR TITLE
[Fix] Make DiagnosticsReporter check scheme before converting to File

### LINKED ISSUE #4305: DiagnosticsReporter causes "AssertionError: assertion failed: Expected protocol to be 'file' or empty in URI jar:file..."
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Upgraded SBT from `1.1.6` to `1.2.0`

## problem
Suddenly application stopped compiling (`sbt compile`), with following error:
```
[error] java.lang.RuntimeException: java.lang.AssertionError: assertion failed: Expected protocol to be 'file' or empty in URI jar:file:///C:/Users/user/.ivy2/cache/com.diffplug.durian/durian/jars/durian-3.4.0.jar!/com/diffplug/common/base/Errors.class
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
[error]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
[error]         at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:154)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$11(AnalyzingJavaCompiler.scala:130)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error]         at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:120)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:105)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1517)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1491)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[error]         at java.base/java.lang.Thread.run(Thread.java:844)
```
Going back to `1.1.6` makes the project to compile again

## expectation
It should compile.

### PR DESCRIPTION
**Pull request by lloydmeta**
Closes: https://github.com/sbt/sbt/issues/4305

DiagnosticsReporter was eagerly turning URIs into Files without checking whether or not the URI is indeed a file. This adds a check to make sure that the scheme is defined (isAbsolute) before doing the conversion, and calling `getAbsolutePath.`

@eed3si9n this targets `develop` and https://github.com/sbt/sbt/issues/4305 has `1.4.0` as the target version.. is there any way to get this on `1.3.x`? I will gladly do the work to backport if needed.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=pull/719/head&io=develop&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

File: internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/DiagnosticsReporter.scala [hunk 1]
```diff
@@ -104,7 +104,13 @@ object DiagnosticsReporter {
         }
 
       val source: Option[JavaFileObject] = Option(d.getSource)
-      val sourcePath: Option[String] = source map (obj => IO.toFile(obj.toUri).getAbsolutePath)
+      val sourcePath: Option[String] = source.map { obj =>
+        val uri = obj.toUri
+        if (uri.isAbsolute && uri.getScheme == "file")
+          IO.toFile(uri).getAbsolutePath
+        else
+          uri.toString
```
Comment (eed3si9n) [inline internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/DiagnosticsReporter.scala:112]: The error case reported on the original issue was `jar:file:///C:/Users/user/.ivy2/cache/com.diffplug.durian/durian/jars/durian-3.4.0.jar!/com/diffplug/common/base/Errors.class`. In this case, I think it would be good to extract the `file` portion out of `jar:` and return the absolute path for `durian-3.4.0.jar`. There's some code that splits the jar part and the in-jar path in https://github.com/sbt/zinc/blob/develop/internal/zinc-classfile/src/main/scala/sbt/internal/inc/JarUtils.scala.

Comment (lloydmeta) [reply internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/DiagnosticsReporter.scala:112]: JarUtils didn't seem to have the splitting logic needed to handle this so I went with using `IO.urlAsFile` in the case where the URI is absolute.

https://github.com/sbt/io/blob/d3297b56297a524baf5982661170edfdb8a6823e/io/src/main/scala/sbt/io/IO.scala#L237-L245

**Comment by lloydmeta** [comment]
@eed3si9n build is now failing on an unrelated problem.

**Comment by eed3si9n** [comment]
I can fix that.

**Comment by lloydmeta** [comment]
@eed3si9n just checking up on this. This 1.5 year old issue is currently threatening to force us to move back to 1.2.x.

**Comment by eed3si9n** [comment]
Looks like the PR validation is passing. So this is good to go.

**Review by eed3si9n — APPROVED** [review]
