### PR TITLE
Fix #127: Use unexpanded names

### LINKED ISSUE #127: Compilation of objects in Scala with special access privileges fail to compile
Whenever I try to compile a Java project with inner classes in it using Zinc I get the following stacktrace:

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
java.lang.RuntimeException Failed to find name hashes for com.example.allang.zinc_test.A.Inner
    at scala.sys.package$.error(package.scala:27)
    at sbt.internal.inc.AnalysisCallback.nameHashesForCompanions(Compile.scala:263)
    at sbt.internal.inc.AnalysisCallback.sbt$internal$inc$AnalysisCallback$$analyzeClass(Compile.scala:270)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1$$anonfun$8.apply(Compile.scala:280)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1$$anonfun$8.apply(Compile.scala:280)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:46)
    at scala.collection.SetLike$class.map(SetLike.scala:92)
    at scala.collection.mutable.AbstractSet.map(Set.scala:46)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1.apply(Compile.scala:280)
    at sbt.internal.inc.AnalysisCallback$$anonfun$addProductsAndDeps$1.apply(Compile.scala:276)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:151)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
    at sbt.internal.inc.AnalysisCallback.addProductsAndDeps(Compile.scala:276)
    at sbt.internal.inc.AnalysisCallback.get(Compile.scala:235)
    at sbt.internal.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:79)
    at sbt.internal.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:76)
    at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:63)
    at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:37)
    at sbt.internal.inc.Incremental$$anonfun$1.apply(Incremental.scala:73)
    at sbt.internal.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
    at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:101)
    at sbt.internal.inc.Incremental$.compile(Incremental.scala:71)
    at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:59)
    at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:162)
    at sbt.internal.inc.IncrementalCompilerImpl.incrementalCompile(IncrementalCompilerImpl.scala:107)
    at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:51)
    at com.zt.jrebel.android.java.incremental.ZincExecutor.execute(ZincExecutor.java:117)
    at com.zt.jrebel.android.java.incremental.ZincExecutor.execute(ZincExecutor.java:103)
    at com.zt.jrebel.android.java.incremental.SourcePreCompiler.precompileSources(SourcePreCompiler.java:38)
    at com.zt.jrebel.android.java.incremental.JavaIncrementalCompiler.parseIncremental(JavaIncrementalCompiler.java:173)
    at com.zt.jrebel.android.java.incremental.JavaIncrementalCompiler.compile(JavaIncrementalCompiler.java:75)
    at com.zt.jra.bundled.compilation.JrJavacAction.execute(JrJavacAction.java:77)
    at com.zt.jra.bundled.compilation.JrJavacAction.execute(JrJavacAction.java:26)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by jvican**
It looks like scalac encodes access rights of objects in their names. To
make sure that we get the right simple names, we need to use
`unexpandedName` instead of `name` which will decipher these access
rights and return their simple names instead (with all the previous `$$`
prefixes stripped out).

Fix #127

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?zinc=pull/431/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by jvican** [comment]
Damn, I forgot to add the "Fix ..." in the commit message and not the title.

**Comment by jvican** [comment]
This is ready for review.

**Review by dwijnand — APPROVED** [review]

File: zinc/src/sbt-test/source-dependencies/unexpanded-names/Foo.scala [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    private[Foo] object Bar
+    class Baz {
+      private[Baz] object Bazz
+    }
+  }
+
+  object Foo {
+    private[issue127] class Bippy
+    // This one is problematic because of expanded names
+    private[issue127] object Bippy
```
Comment (Duhemm) [inline zinc/src/sbt-test/source-dependencies/unexpanded-names/Foo.scala:17]: I thought @eed3si9n said no `Bippy`s? 😝

**Review by Duhemm — APPROVED** [review]
LGTM!

File: zinc/src/sbt-test/source-dependencies/unexpanded-names/Foo.scala (hunk 1 above)
Comment (dwijnand) [reply zinc/src/sbt-test/source-dependencies/unexpanded-names/Foo.scala:17]: Dingos are also available.
